### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by FeisEater** [vastus/vorm-example#1]
Repo ladattu 14.4.2014 klo 15:00

Ensimmäiseksi mainitkoon, että projektisi koodin kieli ei ole lainkaan minulle tuttua (taitaa olla rubya?). Tästä huolimatta ymmärsin suurimmaksi osaksi mitä koodissa tapahtui, mikä kertoo jotain lupaavaa koodin selkeyden kannalta. Selvästi luokat ja metodit ovat selkeästi nimetty.
Ilmeisesti lib/model.rb on ekstraktoitu koodia, mitä konkreettiset malliluokat tulevat käyttämään. Kuitenkin siinä esiintyy koodia liittyen häshäykseen, mitä ymmärtääkseni vain User malliluokka käyttää. Voisiko tämä koodi sijaita eksklusiivisesti Userin koodissa?
Monet .rb tiedostot ovat haiskahtavan pitkiä, varsinkin lib/model.rb. En tiedä kuinka relevantti tämä huomio on rubyn käytänteille. Metodit ainakin pysyivät lyhyinä kaikkialla koodissa.
Useassa kontrolleriluokassa esiintyi check_ownership määrittely. Pystyisikö tämän määrittää vain kerran?
Huomasin että testaat koodiasi, mikä on hienoa. Varsinkin kun sitä ei tsohan tehtävänannoissa vaadittu.

**Comment by vastus** [comment]
Oikeen hyvät pointit, ja kieli on Ruby :+1:. Model-luokka toimii yläluokkana kantaan mapattaville tauluille, ja on todellakin täynnä tavaraa. Tiedostossa sijaitsevat modulet tulee aikanaan olemaan omissa tiedostoissaan, mutta ovat vielä tässä vaiheessa samassa. Ja 'persistable' tagatut metodit tulee omaan moduliinsa. Hashaykseen liittyen on totta, että vain User käyttää BCryptin tarjoamaa hashaysta, mutta Modelissa näkyvät Hash-koodipätkät ovat hajautustaulun konstruktoreita, jos näitä tarkotit. Ja kyllä, check_ownership on kopipastaa, joka eriytetään ;) Cheers
